In [1]:
import pandas as pd
from biom import Table
from biom.util import biom_open
import numpy as np
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

## HIV-HNRC

In [7]:
#read-in HNRC-HIV data
hiv_feature = pd.read_csv('../data/HNRC_HIV_feature_table_filtered.tsv', sep='\t', index_col=0)
hiv_metabolomics = pd.read_csv('../data/HNRC_HIV_metabolomics_ft.csv', index_col=0)
hiv_metadata = pd.read_csv('../data/HNRC_HIV_metadata.tsv', sep='\t', index_col=0)

In [21]:
#match index order of metadata
hiv_feature = hiv_feature.loc[hiv_metadata.index]
hiv_metabolomics = hiv_metabolomics.loc[hiv_metadata.index]

In [22]:
print(hiv_feature.shape)
display(hiv_feature.head())
print(hiv_metabolomics.shape)
display(hiv_metabolomics.head())
print(hiv_metadata.shape)
display(hiv_metadata.head())

(265, 915)

,G000006865,G000006925,G000007325,G000007465,G000007525,G000007785,G000008345,G000008865,G000008925,G000009925,...,G902363425,G902363565,G902363595,G902363685,G902363725,G902363825,G902364485,G902377395,G902387315,G902765685
#SampleID,,,,,,,,,,,,,,,,,,,,,
X3139655,154.0,6215.0,1.0,5.0,1387.0,348.0,1.0,7958.0,32.0,4168.0,...,319.0,981.0,496.0,6064.0,953.0,3677.0,1538.0,84.0,542.0,17346.0
X3145275,1566.0,4.0,2.0,468.0,420.0,228.0,4.0,4.0,65.0,2438.0,...,1406.0,2015.0,10445.0,171934.0,22037.0,3260.0,2060.0,151.0,1712.0,1.0
x3151907,70.0,99.0,1.0,2.0,508.0,6.0,0.0,131.0,6.0,2788.0,...,3438.0,1577.0,492.0,17363.0,1952.0,3323.0,803.0,30.0,938.0,1.0
X3143799,25.0,515.0,0.0,0.0,8867.0,57.0,0.0,625.0,2.0,6496.0,...,315.0,3533.0,2766.0,31564.0,2046.0,3483.0,2059.0,103.0,1588.0,0.0
X3143566,0.0,38730.0,0.0,0.0,212.0,19.0,1.0,45220.0,8.0,23340.0,...,30489.0,728.0,409.0,1017.0,758.0,234.0,1175.0,21.0,251.0,0.0

(265, 17729)

,127,8773,14968,6939,3732,5189,1763,752,2832,11734,...,28180,19389,30333,23657,29658,25063,23675,28301,29764,29765
#SampleID,,,,,,,,,,,,,,,,,,,,,
X3139655,0.0,0.0,0.0,43325.688,3644838.8,0.0,0.0,0.0,0.0,14911.899,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
X3145275,0.0,0.0,0.0,0.000,0.0,0.0,0.0,790976.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
x3151907,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
X3143799,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
X3143566,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

(265, 7)

,depression,atypical antipsychotic,antimalarial,HMG-CoA reductase inhibitor (statin),other antidepressants,antiarrhythmic,hiv_status
#SampleID,,,,,,,
X3139655,True,False,True,True,True,False,HIV+
X3145275,True,True,True,True,False,False,HIV+
x3151907,True,False,True,True,True,True,HIV-
X3143799,True,True,True,True,True,True,HIV+
X3143566,True,True,False,False,False,False,HIV+

## U19-Wisconsin

In [15]:
#read-in U19-Wisconsin data
u19_feature = pd.read_csv('../data/U19_Wisconsin_feature_table_filtered.tsv', sep='\t', index_col=0)
u19_metabolomics = pd.read_csv('../data/U19_Wisconsin_metabolomics_ft.csv', index_col=0)
u19_metadata = pd.read_csv('../data/U19_Wisconsin_matched_metadata.tsv', sep='\t', index_col=0)

In [44]:
#match index order of metadata
u19_feature = u19_feature.loc[u19_metadata.index]
#add 13663 to id names
u19_metabolomics.index = ['13663.{}'.format(i) for i in u19_metabolomics.index]
u19_metabolomics = u19_metabolomics.loc[u19_metadata.index]

In [45]:
print(u19_feature.shape)
display(u19_feature.head())
print(u19_metabolomics.shape)
display(u19_metabolomics.head())
print(u19_metadata.shape)
display(u19_metadata.head())

(238, 904)

,G000006865,G000006925,G000007325,G000007465,G000007525,G000007785,G000008865,G000009205,G000009925,G000010145,...,G902363425,G902363565,G902363595,G902363685,G902363725,G902363825,G902364485,G902387315,G902406265,G902765685
#SampleID,,,,,,,,,,,,,,,,,,,,,
13663.mars00001,2.0,28.0,3.0,0.0,549.0,2.0,31.0,61.0,767.0,0.0,...,784.0,501.0,129.0,810.0,151.0,2020.0,1326.0,803.0,85.0,0.0
13663.mars00002,22.0,50.0,0.0,2.0,14435.0,15.0,53.0,246.0,3314.0,1.0,...,1134.0,955.0,300.0,2902.0,439.0,2002.0,1153.0,3746.0,71.0,0.0
13663.mars00003,10.0,1.0,0.0,0.0,3836.0,5.0,0.0,172.0,3379.0,0.0,...,590.0,674.0,268.0,11839.0,358.0,12217.0,290.0,345.0,15.0,2.0
13663.mars00004,0.0,1.0,0.0,3.0,8.0,5.0,1.0,15.0,951.0,0.0,...,213.0,451.0,287.0,2331.0,100.0,434.0,1099.0,218.0,27.0,59466.0
13663.mars00005,442.0,8.0,0.0,3.0,632.0,7.0,8.0,266.0,6344.0,0.0,...,1266.0,1284.0,133.0,993.0,176.0,394.0,1076.0,1280.0,91.0,0.0

(238, 1439)

,Alpha-pyrrolidinovalerophenone,Amphetamine,"""((4R)-4-((3R,5S,7R,9S,10S,13R,14S,17R)-3,7-dihydroxy-10,13-dimethylhexadecahydro-1H-cyclopenta[a]phenanthren-17-yl)-2,2-dimethylpentanoyl)glycine""","""(2E)-N-(3-acetylphenyl)-3-(3,4-dimethoxyphenyl)prop-2-enamide CollisionEnergy:102040""","""(2R,3R,6R)-3-hydroxy-2-methyl-6-((3R,5S,7R,8R,9S,10S,12S,13R,14S,17R)-3,7,12-trihydroxy-10,13-dimethylhexadecahydro-1H-cyclopenta[a]phenanthren-17-yl)heptanoic acid""","""(2S,3S)-6-((3R,5S,7R,9S,10S,13R,14S,17R)-3,7-dihydroxy-10,13-dimethylhexadecahydro-1H-cyclopenta[a]phenanthren-17-yl)-3-hydroxy-2-methylheptanoic acid""","""(2S,3S,6R)-3-hydroxy-2-methyl-6-((3R,5S,7R,8R,9S,10S,12S,13R,14S,17R)-3,7,12-trihydroxy-10,13-dimethylhexadecahydro-1H-cyclopenta[a]phenanthren-17-yl)heptanoic acid""","""(2S,4S,5S,3R)-2,5-bis(3-pyridylcarbonyloxymethyl)-2-hydroxy-4-(3-pyridylcarbon yloxy)oxolan-3-yl pyridine-3-carboxylate CollisionEnergy:205060""","""(2S,6R)-2-methyl-6-((3R,5S,7R,9S,10S,12S,13R,14S,17R)-3,7,12-trihydroxy-10,13-dimethylhexadecahydro-1H-cyclopenta[a]phenanthren-17-yl)heptanoic acid""","""(3,4-dimethoxyphenyl)-N-(6-ethyl-2-methylphenyl)carboxamide CollisionEnergy:205060""",...,quinine,salicylic acid CollisionEnergy:102040,skullcapflavone II,sophocarpine,spiciferinone,suberosin,syringaresinol,triamterene CollisionEnergy:102040,veratramine,verruculotoxin
#SampleID,,,,,,,,,,,,,,,,,,,,,
13663.mars00001,0.0,0.0,1196.2805,0.0,0.0,34817.0860,0.000,0.0,0.00000,0.00,...,115712.9654,0.00000,0.0,8732.7790,0.0,6193.272,6252.2744,0.0,0.0,47533.521
13663.mars00002,0.0,0.0,0.0000,0.0,0.0,741.0923,0.000,0.0,439.73346,0.00,...,4403.8740,0.00000,0.0,2428.8762,0.0,21778.967,16584.1290,0.0,0.0,31202.126
13663.mars00003,0.0,0.0,0.0000,0.0,0.0,0.0000,11401.655,0.0,0.00000,0.00,...,0.0000,0.00000,0.0,0.0000,0.0,0.000,19864.4060,0.0,0.0,56365.938
13663.mars00004,0.0,0.0,0.0000,0.0,0.0,0.0000,0.000,0.0,0.00000,137090.23,...,51853.9140,779.94586,0.0,19275.6880,0.0,5948.963,0.0000,0.0,0.0,47385.734
13663.mars00005,0.0,0.0,0.0000,0.0,0.0,0.0000,0.000,0.0,227.38763,0.00,...,1988.7565,1075.39447,0.0,2095.7493,0.0,344.060,7867.3916,0.0,0.0,49171.259

(238, 67)

,seq_id,reggieid,unique_id,marsid,visit,mars_age,uw_seq_run1,uw_seq_run2,uw_seq_run3,uw_seq_run4,...,apoe_e2,reggieid_y,diff_med,med,freq,atc,atcdesc,source,medication_status,amyloid
#SampleID,,,,,,,,,,,,,,,,,,,,,
13663.mars00001,mars00001-v1,3720.0,mars00001-v1,mars00001,1.0,76.45,Oct2016,NaN,Sept2018,NaN,...,3.0,3720.0,0.11,Spring Valley Cod Liver Oil,1,C10AX06,omega-3-triglycerides incl. other esters and a...,WRAP,medicated,NaN
13663.mars00002,mars00002-v1,3959.0,mars00002-v1,mars00002,1.0,65.28,Oct2016,Feb2017,Sept2018,Sept2019,...,4.0,3959.0,0.18,Fish Oil,1,C10AX06,omega-3-triglycerides incl. other esters and a...,WRAP,medicated,NaN
13663.mars00003,mars00003-v1,3122.0,mars00003-v1,mars00003,1.0,61.57,Oct2016,Feb2017,Sept2018,Sept2019,...,3.0,3122.0,0.21,Levothyroxin,1,H03AA,Thyroid hormones,WRAP,medicated,Negative
13663.mars00004,mars00004-v1,1676.0,mars00004-v1,mars00004,1.0,57.98,Oct2016,NaN,Sept2018,NaN,...,3.0,1676.0,0.36,Walgreens Aspirin,7,N02BA,Salicylic acid and derivatives,WRAP,medicated,NaN
13663.mars00005,mars00005-v1,3762.0,mars00005-v1,mars00005,1.0,76.03,Oct2016,Feb2017,Sept2018,Sept2019,...,4.0,3762.0,1.01,Simply Right Triple Omega 3 Fish Oil,1,C10AX06,omega-3-triglycerides incl. other esters and a...,WRAP,medicated,Positive

In [46]:
#save formatted data
hiv_feature.to_csv('../data/HNRC_HIV_feature_table_formatted.tsv', sep='\t')
hiv_metabolomics.to_csv('../data/HNRC_HIV_metabolomics_ft_formatted.csv')
u19_feature.to_csv('../data/U19_Wisconsin_feature_table_formatted.tsv', sep='\t')
u19_metabolomics.to_csv('../data/U19_Wisconsin_metabolomics_ft_formatted.csv')